files:
- generatedChecksum: 806D761A2549A6BB5233D0BBC4078B84
  logicalPath: config/Bootloader/bootloader
  name: bootloader.c
  physicalPath: bootloader
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9BA057D682AF9A490A69A86759121B67
- generatedChecksum: 03109DB0149A21099C16979325E4E904
  logicalPath: config/Bootloader
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: EE58F93AE0804059103A90CAF4E58716
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 7ADEB11B24FF517C6852A3BE46534C9E
  logicalPath: config/Bootloader/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7ADEB11B24FF517C6852A3BE46534C9E
- generatedChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
  logicalPath: config/Bootloader/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
- generatedChecksum: 73655D0141303A622897223776142085
  logicalPath: config/Bootloader/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 73655D0141303A622897223776142085
- generatedChecksum: 619582D6B654C36BD25699B19A5174B2
  logicalPath: config/Bootloader/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 619582D6B654C36BD25699B19A5174B2
- generatedChecksum: CA41C0116AA86AA82F796A658ADFE1E7
  logicalPath: config/Bootloader/peripheral/nvm
  name: plib_nvm.c
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: SOURCE
  userChecksum: CA41C0116AA86AA82F796A658ADFE1E7
- generatedChecksum: CB7A5E17457F3268C31238F6CA69E413
  logicalPath: config/Bootloader/peripheral/tmr
  name: plib_tmr2.c
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: CB7A5E17457F3268C31238F6CA69E413
- generatedChecksum: 8B73AC821989A0DB630F9ED0FDDC86AD
  logicalPath: config/Bootloader/peripheral/uart
  name: plib_uart1.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8B73AC821989A0DB630F9ED0FDDC86AD
- generatedChecksum: 421E0E3D113AC4742E1A755A321D08DF
  logicalPath: config/Bootloader/peripheral/wdt
  name: plib_wdt.c
  physicalPath: peripheral/wdt
  security: NON_SECURE
  type: SOURCE
  userChecksum: 421E0E3D113AC4742E1A755A321D08DF
- generatedChecksum: 990DBFB8486BC4A7F3871187FE5C13C3
  logicalPath: config/Bootloader/bootloader
  name: bootloader.h
  physicalPath: bootloader
  security: NON_SECURE
  type: HEADER
  userChecksum: 990DBFB8486BC4A7F3871187FE5C13C3
- generatedChecksum: 75F78E1337C81266079C11878522C07D
  logicalPath: config/Bootloader
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 75F78E1337C81266079C11878522C07D
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/Bootloader
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/Bootloader/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 0EA600D4DBA17C02F74FD5C7BE8F56B0
  logicalPath: config/Bootloader/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 0EA600D4DBA17C02F74FD5C7BE8F56B0
- generatedChecksum: 430C9486AF3942CB6998E7BCA3583186
  logicalPath: config/Bootloader/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 430C9486AF3942CB6998E7BCA3583186
- generatedChecksum: B8FD4B4CF945883776798F51F33BA8DE
  logicalPath: config/Bootloader/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: B8FD4B4CF945883776798F51F33BA8DE
- generatedChecksum: C0FAA39AF4F7B047388A41E19673A60D
  logicalPath: config/Bootloader/peripheral/nvm
  name: plib_nvm.h
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: HEADER
  userChecksum: C0FAA39AF4F7B047388A41E19673A60D
- generatedChecksum: 612994C7F3C27F2CFA2621C1F65D4068
  logicalPath: config/Bootloader/peripheral/tmr
  name: plib_tmr2.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: 612994C7F3C27F2CFA2621C1F65D4068
- generatedChecksum: D948F2CE092CAB556EF299D3CCD83A55
  logicalPath: config/Bootloader/peripheral/tmr
  name: plib_tmr_common.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D948F2CE092CAB556EF299D3CCD83A55
- generatedChecksum: ECAA9081AA8CB2D6C487A124CE10E189
  logicalPath: config/Bootloader/peripheral/uart
  name: plib_uart1.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: ECAA9081AA8CB2D6C487A124CE10E189
- generatedChecksum: 91611515A95D92B82B7F4064C16D122B
  logicalPath: config/Bootloader/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 91611515A95D92B82B7F4064C16D122B
- generatedChecksum: 2AD7259D0E303CE06622D0F1A6BBEC13
  logicalPath: config/Bootloader/peripheral/wdt
  name: plib_wdt.h
  physicalPath: peripheral/wdt
  security: NON_SECURE
  type: HEADER
  userChecksum: 2AD7259D0E303CE06622D0F1A6BBEC13
- generatedChecksum: CAC44960D20AEC03CF4B325A1CD2877C
  logicalPath: config/Bootloader
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CAC44960D20AEC03CF4B325A1CD2877C
- generatedChecksum: 7EF127A8A2E722A0C63CA22F94BB65B0
  logicalPath: ''
  name: btl.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 7EF127A8A2E722A0C63CA22F94BB65B0
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/Bootloader;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32
  delimiter: ''
  key: optimization-level
  security: NON_SECURE
  value: -O2
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/Bootloader;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
