format_version: v1.0
type: UniqueComponent
attributes: {id: uart1}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BAUD_RATE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '921600'}
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: '26'}
  - type: Comment
    attributes: {id: UART_BAUD_PER_ERROR_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '*** Baud Error = 0.4693 % ***'}
  - type: KeyValueSet
    attributes: {id: UART_BRGH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: '0'}
  - type: Integer
    attributes: {id: UART_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: '100000000'}
  - type: File
    attributes: {id: UART_HEADER}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: ../peripheral/uart_00734/templates/plib_uart.h.ftl}
  - type: Boolean
    attributes: {id: UART_INTERRUPT_MODE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: 'false'}
  - type: KeyValueSet
    attributes: {id: UART_OPERATING_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: '0'}
      - type: User
        attributes: {value: '0'}
  - type: Boolean
    attributes: {id: UART_RING_BUFFER_MODE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: 'false'}
  - type: File
    attributes: {id: UART_SOURCE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: ../peripheral/uart_00734/templates/plib_uart.c.ftl}
  - type: Integer
    attributes: {id: UART_TX_RING_BUFFER_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '10000'}
  - type: KeyValueSet
    attributes: {id: UART_UEN_SELECT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Hex
    attributes: {id: UMODE_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: '520'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: UART1_UART}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: uart_bootloader}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: btl_UART_dependency}
- type: ElementPosition
  attributes: {x: '289', y: '114', id: uart1}
